server:
  port: 8081

spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: "jdbc:${DB_URL_AUTH}"
    username: ${DB_USERNAME_AUTH}
    password: ${DB_PASSWORD_AUTH}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: auth
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "${SECRET_KEY_JWT}"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  config:
    import: classpath:key-redis.yml

jwt:
  issuer: flood-alert-auth-service
  access-token-expiration: 3600 # 24 hours
  refresh-token-expiration: 604800 # 7 days

firebase:
  config:
    path: ${FIREBASE_CONFIG_PATH:classpath:firebase-key.json}

app:
  kafka:
    topic:
      fcm-token: ${KAFKA_FCM_TOKEN_TOPIC:fcm-token-events}

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: INFO