server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:ingention-service}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms


mqtt:
  borker-url: ${MQTT_BROKER_URL:tcp://localhost:1883}
  client-id: ${MQTT_CLIENT_ID:ingention-service}-${random.uuid}
  topic-pattern: ${MQTT_TOPIC_PATTERN:floodguard/sensors/+/telemetry}
  qos: ${MQTT_QOS:1}
  auto-reconnect: ${MQTT_AUTO_RECONNECT:true}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topic: ${KAFKA_TOPIC:iot-raw}
  producer:
    key-serializer: ${KAFKA_PRODUCER_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
    value-serializer: ${KAFKA_PRODUCER_VALUE_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
    acks: ${KAFKA_PRODUCER_ACKS:all}
    retries: ${KAFKA_PRODUCER_RETRIES:3}

