server:
  port: 8083
spring:
  application:
    name: floodcore-service
  datasource:
    url: "jdbc:${DB_URL_FLOODCORE}"
    username: ${DB_USERNAME_FLOODCORE}
    password: ${DB_PASSWORD_FLOODCORE}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        default_schema: flood_core
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 5000
      lettuce:
        pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: -1ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  config:
    import: classpath:key-redis.yml

app:
  kafka:
    topic:
      lifecycle: ${KAFKA_LIFECYCLE_TOPIC:flood-lifecycle-events}
      sensor-health-sync: ${KAFKA_SENSOR_HEALTH_SYNC_TOPIC:sensor-health-sync}
      user-report: ${KAFKA_USER_REPORT_TOPIC:user-report-events}
    consumer:
      core-sync:
        group-id: ${KAFKA_CORE_SYNC_GROUP_ID:core-map-sync-group}
      sensor-health:
        group-id: ${KAFKA_SENSOR_HEALTH_GROUP_ID:sensor-health-batch-group}
        concurrency: ${KAFKA_SENSOR_HEALTH_CONCURRENCY:3}
        max-poll-records: ${KAFKA_SENSOR_HEALTH_MAX_POLL_RECORDS:50}

flood-processor:
  url: ${FLOOD_PROCESSOR_URL:http://localhost:8084}

firebase:
  storage:
    bucket-name: ${FIREBASE_STORAGE_BUCKET:flood-alert-c4f24.firebasestorage.app}
    service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:classpath:firebase-key.json}
    signed-url-duration-minutes: ${FIREBASE_SIGNED_URL_DURATION:15}

integration:
  ors:
    api-url: "https://api.openrouteservice.org/v2/directions/driving-car/geojson"
    api-key: ${ORS_API_KEY}